export const routes = {
  root: '/',
  api: '/api',
  auth: '/auth',
  login: '/login',
  shelves: '/shelves',
  qID: '/:id',
  byIDs: '/by-ids',
  byUserID: '/by-user-id',
  allIDs: '/all-ids',
  products: '/products',
  reports: '/reports',
  apiDocs: '/api-docs',
  simulation: '/simulation',
};
